services:
  frontend:
    container_name: ${BENCHMARK_RUN_ID}_frontend
    ports: !reset []
  nginx:
    container_name: ${BENCHMARK_RUN_ID}_nginx
    ports: !reset []
  backend:
    container_name: ${BENCHMARK_RUN_ID}_backend
    ports: !reset []
  db:
    container_name: ${BENCHMARK_RUN_ID}_db
    ports: !reset []
  db_test:
    container_name: ${BENCHMARK_RUN_ID}_db_test
    ports: !reset []
